/**
 * Canonical list of all wellness modalities.
 * Source of truth for the directory — must stay in sync with database and pipelines.
 * Total: 44 modalities
 */
export const ALL_MODALITIES = [
  'Acupuncture',
  'Alternative Therapy',
  'Art Therapy',
  'Astrology',
  'Ayurveda',
  'Birth Doula',
  'Breathwork',
  'Chiropractic',
  'Counseling',
  'Craniosacral',
  'Dentistry',
  'Energy Healing',
  'Family Constellation',
  'Fitness',
  'Functional Medicine',
  'Hawaiian Healing',
  'Herbalism',
  'Hypnotherapy',
  'IV Therapy',
  'Life Coaching',
  'Lomilomi / Hawaiian Healing',
  'Longevity',
  'Massage',
  'Meditation',
  'Midwife',
  'Nature Therapy',
  'Naturopathic',
  'Nervous System Regulation',
  'Network Chiropractic',
  'Nutrition',
  'Osteopathic',
  'Physical Therapy',
  'Psychic',
  'Psychotherapy',
  'Reiki',
  'Ritualist',
  'Somatic Therapy',
  'Soul Guidance',
  'Sound Healing',
  'TCM (Traditional Chinese Medicine)',
  'Trauma-Informed Care',
  'Watsu / Water Therapy',
  "Women's Health",
  'Yoga',
];
