/**
 * AdminQueue — placeholder tab for near-miss review queue.
 * Extracted from AdminPanel.tsx for maintainability.
 */
import { Card, CardContent } from '@/components/ui/card';

export function AdminQueue() {
  return (
    <div className="space-y-6">
      <Card className="border-amber-200 bg-amber-50/40">
        <CardContent className="pt-6">
          <h3 className="text-lg font-semibold mb-3 text-amber-900">Near-Miss Review Queue</h3>
          <p className="text-sm text-amber-800 mb-4">
            Near-miss review records are practitioners or wellness centers that score <strong>70–84% name similarity</strong> to existing database records during the deduplication step. They need manual review to decide:
          </p>
          <ul className="list-disc list-inside text-sm text-amber-800 space-y-1 ml-2">
            <li><strong>Accept as New</strong> — the match score is misleading; insert as a new record</li>
            <li><strong>Merge with Existing</strong> — confirm it's a duplicate and manually merge the data</li>
            <li><strong>Discard</strong> — it's spam or irrelevant; skip it</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="pt-6">
          <h4 className="font-semibold mb-3">How to Access Review Records</h4>
          <p className="text-sm text-gray-600 mb-4">
            Near-miss records are generated by the pipeline deduplication script and stored in <code className="font-mono bg-gray-100 px-2 py-1 rounded text-xs">pipeline/output/gm_review.jsonl</code>. A future enhancement will load these directly into this admin panel. For now, use the workflow below:
          </p>

          <div className="space-y-4">
            <div className="space-y-2">
              <h5 className="text-sm font-medium">1. Run the pipeline dedup script</h5>
              <div className="bg-gray-800 text-gray-100 p-3 rounded text-xs font-mono overflow-x-auto">
                <pre>cd pipeline
python scripts/12_gm_dedup.py --island big_island</pre>
              </div>
            </div>

            <div className="space-y-2">
              <h5 className="text-sm font-medium">2. Preview the review queue (first 50 records)</h5>
              <div className="bg-gray-800 text-gray-100 p-3 rounded text-xs font-mono overflow-x-auto">
                <pre>cd pipeline
{`jq '. | {"name", "_review_reason", "_possible_match_name"}' \\
  output/gm_review.jsonl | head -50`}</pre>
              </div>
            </div>

            <div className="space-y-2">
              <h5 className="text-sm font-medium">3. View full record details</h5>
              <div className="bg-gray-800 text-gray-100 p-3 rounded text-xs font-mono overflow-x-auto">
                <pre>cd pipeline
jq '.' output/gm_review.jsonl | less</pre>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card className="border-blue-200 bg-blue-50/40">
        <CardContent className="pt-6">
          <h4 className="font-semibold mb-2 text-blue-900">Future Enhancement</h4>
          <p className="text-sm text-blue-800">
            A future release will automatically import near-miss records into a Supabase <code className="font-mono bg-blue-100 px-1 rounded text-xs">pipeline_review_queue</code> table, and this tab will show an interactive review interface with accept/merge/discard buttons for each record.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
