INSERT INTO taxonomy_aliases (term_id, alias) VALUES
((SELECT id FROM taxonomy_terms WHERE slug = 'acupuncture' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'acupuncturist'),
((SELECT id FROM taxonomy_terms WHERE slug = 'acupuncture' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'chinese acupuncture'),
((SELECT id FROM taxonomy_terms WHERE slug = 'acupuncture' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'japanese acupuncture'),
((SELECT id FROM taxonomy_terms WHERE slug = 'acupuncture' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'auricular acupuncture'),
((SELECT id FROM taxonomy_terms WHERE slug = 'tcm' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'chinese medicine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'tcm' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'oriental medicine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'tcm' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'traditional chinese medicine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'tcm' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'cupping'),
((SELECT id FROM taxonomy_terms WHERE slug = 'tcm' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'moxibustion'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'bodywork'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'body work'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'deep tissue'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'swedish massage'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'therapeutic massage'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'sports massage'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'hot stone'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'trigger point'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'neuromuscular'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'lymphatic'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'lymph'),
((SELECT id FROM taxonomy_terms WHERE slug = 'massage' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'lmt'),
((SELECT id FROM taxonomy_terms WHERE slug = 'craniosacral' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'cranio sacral'),
((SELECT id FROM taxonomy_terms WHERE slug = 'craniosacral' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'cranio'),
((SELECT id FROM taxonomy_terms WHERE slug = 'craniosacral' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'cst'),
((SELECT id FROM taxonomy_terms WHERE slug = 'craniosacral' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'biodynamic'),
((SELECT id FROM taxonomy_terms WHERE slug = 'craniosacral' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'craniosacral therapy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'lomilomi-hawaiian-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'lomilomi'),
((SELECT id FROM taxonomy_terms WHERE slug = 'lomilomi-hawaiian-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'lomi'),
((SELECT id FROM taxonomy_terms WHERE slug = 'lomilomi-hawaiian-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'lomi lomi'),
((SELECT id FROM taxonomy_terms WHERE slug = 'lomilomi-hawaiian-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'hawaiian massage'),
((SELECT id FROM taxonomy_terms WHERE slug = 'watsu-water-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'watsu'),
((SELECT id FROM taxonomy_terms WHERE slug = 'watsu-water-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'water therapy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'watsu-water-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'aquatic therapy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'watsu-water-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'water healing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'watsu-water-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'aquatic bodywork'),
((SELECT id FROM taxonomy_terms WHERE slug = 'myofascial-release' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'myofascial'),
((SELECT id FROM taxonomy_terms WHERE slug = 'myofascial-release' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'mfr'),
((SELECT id FROM taxonomy_terms WHERE slug = 'myofascial-release' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'fascia'),
((SELECT id FROM taxonomy_terms WHERE slug = 'myofascial-release' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'fascial'),
((SELECT id FROM taxonomy_terms WHERE slug = 'reiki' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'reiki master'),
((SELECT id FROM taxonomy_terms WHERE slug = 'reiki' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'reiki healer'),
((SELECT id FROM taxonomy_terms WHERE slug = 'reiki' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'reiki practitioner'),
((SELECT id FROM taxonomy_terms WHERE slug = 'reiki' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'usui reiki'),
((SELECT id FROM taxonomy_terms WHERE slug = 'sound-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'sound bath'),
((SELECT id FROM taxonomy_terms WHERE slug = 'sound-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'sound healer'),
((SELECT id FROM taxonomy_terms WHERE slug = 'sound-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'gong bath'),
((SELECT id FROM taxonomy_terms WHERE slug = 'sound-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'singing bowl'),
((SELECT id FROM taxonomy_terms WHERE slug = 'sound-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'tuning fork'),
((SELECT id FROM taxonomy_terms WHERE slug = 'sound-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'tibetan bowl'),
((SELECT id FROM taxonomy_terms WHERE slug = 'sound-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'vibrational healing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'energy-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'energy work'),
((SELECT id FROM taxonomy_terms WHERE slug = 'energy-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'energy heal'),
((SELECT id FROM taxonomy_terms WHERE slug = 'energy-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'energy healer'),
((SELECT id FROM taxonomy_terms WHERE slug = 'energy-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'energy medicine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'energy-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'biofield'),
((SELECT id FROM taxonomy_terms WHERE slug = 'energy-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'quantum healing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'energy-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'quantum'),
((SELECT id FROM taxonomy_terms WHERE slug = 'energy-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'pranic'),
((SELECT id FROM taxonomy_terms WHERE slug = 'energy-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'healing touch'),
((SELECT id FROM taxonomy_terms WHERE slug = 'energy-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'hands on healing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'energy-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'light work'),
((SELECT id FROM taxonomy_terms WHERE slug = 'yoga' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'yoga teacher'),
((SELECT id FROM taxonomy_terms WHERE slug = 'yoga' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'yogi'),
((SELECT id FROM taxonomy_terms WHERE slug = 'yoga' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'vinyasa'),
((SELECT id FROM taxonomy_terms WHERE slug = 'yoga' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'hatha'),
((SELECT id FROM taxonomy_terms WHERE slug = 'yoga' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'yin yoga'),
((SELECT id FROM taxonomy_terms WHERE slug = 'yoga' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'kundalini'),
((SELECT id FROM taxonomy_terms WHERE slug = 'yoga' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'ashtanga'),
((SELECT id FROM taxonomy_terms WHERE slug = 'yoga' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'restorative yoga'),
((SELECT id FROM taxonomy_terms WHERE slug = 'yoga' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'yoga therapy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'breathwork' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'breath work'),
((SELECT id FROM taxonomy_terms WHERE slug = 'breathwork' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'pranayama'),
((SELECT id FROM taxonomy_terms WHERE slug = 'breathwork' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'wim hof'),
((SELECT id FROM taxonomy_terms WHERE slug = 'breathwork' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'holotropic'),
((SELECT id FROM taxonomy_terms WHERE slug = 'breathwork' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'rebirthing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'meditation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'mindfulness'),
((SELECT id FROM taxonomy_terms WHERE slug = 'meditation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'guided meditation'),
((SELECT id FROM taxonomy_terms WHERE slug = 'meditation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'zen'),
((SELECT id FROM taxonomy_terms WHERE slug = 'meditation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'stillness'),
((SELECT id FROM taxonomy_terms WHERE slug = 'meditation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'vipassana'),
((SELECT id FROM taxonomy_terms WHERE slug = 'meditation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'transcendental meditation'),
((SELECT id FROM taxonomy_terms WHERE slug = 'somatic-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'somatic'),
((SELECT id FROM taxonomy_terms WHERE slug = 'somatic-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'soma'),
((SELECT id FROM taxonomy_terms WHERE slug = 'somatic-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'somatic experiencing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'somatic-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'somatic practice'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hypnotherapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'hypnosis'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hypnotherapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'hypnotist'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hypnotherapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'hypnotherapist'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hypnotherapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'nlp'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hypnotherapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'neuro linguistic programming'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hawaiian-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'ho oponopono'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hawaiian-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'ho''oponopono'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hawaiian-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'huna'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hawaiian-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'kahuna'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hawaiian-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'aloha spirit'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hawaiian-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'indigenous healing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'hawaiian-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'la''au lapa''au'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ritualist' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'ceremony'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ritualist' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'ritual'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ritualist' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'medicine woman'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ritualist' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'medicine man'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ritualist' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'curandera'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ritualist' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'curandero'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ritualist' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'medicine wheel'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ritualist' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'sacred ceremony'),
((SELECT id FROM taxonomy_terms WHERE slug = 'naturopathic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'naturopath'),
((SELECT id FROM taxonomy_terms WHERE slug = 'naturopathic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'naturopathic doctor'),
((SELECT id FROM taxonomy_terms WHERE slug = 'naturopathic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'nd'),
((SELECT id FROM taxonomy_terms WHERE slug = 'naturopathic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'naturopathic medicine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'functional-medicine' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'integrative medicine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'functional-medicine' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'holistic doctor'),
((SELECT id FROM taxonomy_terms WHERE slug = 'functional-medicine' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'holistic medicine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'functional-medicine' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'functional med'),
((SELECT id FROM taxonomy_terms WHERE slug = 'chiropractic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'chiropractor'),
((SELECT id FROM taxonomy_terms WHERE slug = 'chiropractic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'chiro'),
((SELECT id FROM taxonomy_terms WHERE slug = 'chiropractic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'spinal adjustment'),
((SELECT id FROM taxonomy_terms WHERE slug = 'chiropractic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'chiropractic adjustment'),
((SELECT id FROM taxonomy_terms WHERE slug = 'network-chiropractic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'nse'),
((SELECT id FROM taxonomy_terms WHERE slug = 'network-chiropractic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'network spinal'),
((SELECT id FROM taxonomy_terms WHERE slug = 'network-chiropractic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'network spinal analysis'),
((SELECT id FROM taxonomy_terms WHERE slug = 'osteopathic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'osteopath'),
((SELECT id FROM taxonomy_terms WHERE slug = 'osteopathic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'osteopathy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'osteopathic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'do'),
((SELECT id FROM taxonomy_terms WHERE slug = 'osteopathic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'doctor of osteopathy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'physical-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'physical therapist'),
((SELECT id FROM taxonomy_terms WHERE slug = 'physical-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'pt'),
((SELECT id FROM taxonomy_terms WHERE slug = 'physical-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'rehab'),
((SELECT id FROM taxonomy_terms WHERE slug = 'physical-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'rehabilitation'),
((SELECT id FROM taxonomy_terms WHERE slug = 'physical-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'sports rehab'),
((SELECT id FROM taxonomy_terms WHERE slug = 'dentistry' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'dentist'),
((SELECT id FROM taxonomy_terms WHERE slug = 'dentistry' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'dental'),
((SELECT id FROM taxonomy_terms WHERE slug = 'dentistry' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'holistic dentist'),
((SELECT id FROM taxonomy_terms WHERE slug = 'dentistry' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'biological dentist'),
((SELECT id FROM taxonomy_terms WHERE slug = 'iv-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'iv drip'),
((SELECT id FROM taxonomy_terms WHERE slug = 'iv-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'iv infusion'),
((SELECT id FROM taxonomy_terms WHERE slug = 'iv-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'vitamin drip'),
((SELECT id FROM taxonomy_terms WHERE slug = 'iv-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'nutrient iv'),
((SELECT id FROM taxonomy_terms WHERE slug = 'longevity' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'anti-aging'),
((SELECT id FROM taxonomy_terms WHERE slug = 'longevity' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'biohack'),
((SELECT id FROM taxonomy_terms WHERE slug = 'longevity' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'biohacking'),
((SELECT id FROM taxonomy_terms WHERE slug = 'longevity' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'regenerative medicine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'longevity' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'regenerative'),
((SELECT id FROM taxonomy_terms WHERE slug = 'longevity' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'age reversal'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychotherapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'psychologist'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychotherapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'talk therapy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychotherapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'depth psychology'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychotherapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'jungian'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychotherapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'psychoanalysis'),
((SELECT id FROM taxonomy_terms WHERE slug = 'counseling' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'counselor'),
((SELECT id FROM taxonomy_terms WHERE slug = 'counseling' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'mental health counseling'),
((SELECT id FROM taxonomy_terms WHERE slug = 'counseling' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'licensed counselor'),
((SELECT id FROM taxonomy_terms WHERE slug = 'counseling' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'lpc'),
((SELECT id FROM taxonomy_terms WHERE slug = 'counseling' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'lmhc'),
((SELECT id FROM taxonomy_terms WHERE slug = 'life-coaching' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'life coach'),
((SELECT id FROM taxonomy_terms WHERE slug = 'life-coaching' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'coach'),
((SELECT id FROM taxonomy_terms WHERE slug = 'life-coaching' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'coaching'),
((SELECT id FROM taxonomy_terms WHERE slug = 'life-coaching' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'mentor'),
((SELECT id FROM taxonomy_terms WHERE slug = 'life-coaching' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'executive coach'),
((SELECT id FROM taxonomy_terms WHERE slug = 'life-coaching' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'business coach'),
((SELECT id FROM taxonomy_terms WHERE slug = 'life-coaching' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'wellness coach'),
((SELECT id FROM taxonomy_terms WHERE slug = 'soul-guidance' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'soul guide'),
((SELECT id FROM taxonomy_terms WHERE slug = 'soul-guidance' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'soul work'),
((SELECT id FROM taxonomy_terms WHERE slug = 'soul-guidance' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'soul healing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'soul-guidance' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'soul retrieval'),
((SELECT id FROM taxonomy_terms WHERE slug = 'soul-guidance' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'soul coach'),
((SELECT id FROM taxonomy_terms WHERE slug = 'soul-guidance' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'akashic'),
((SELECT id FROM taxonomy_terms WHERE slug = 'soul-guidance' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'channeling'),
((SELECT id FROM taxonomy_terms WHERE slug = 'soul-guidance' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'channelling'),
((SELECT id FROM taxonomy_terms WHERE slug = 'soul-guidance' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'spirit guide'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma-informed-care' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'trauma care'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma-informed-care' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'trauma therapy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma-informed-care' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'emdr'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma-informed-care' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'ptsd treatment'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma-informed-care' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'trauma recovery'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma-informed-care' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'trauma healing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nervous-system-regulation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'nervous system'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nervous-system-regulation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'polyvagal'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nervous-system-regulation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'vagus nerve'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nervous-system-regulation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'dysregulation'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nervous-system-regulation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'regulation'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nervous-system-regulation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'nervous system support'),
((SELECT id FROM taxonomy_terms WHERE slug = 'family-constellation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'constellation work'),
((SELECT id FROM taxonomy_terms WHERE slug = 'family-constellation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'systemic constellation'),
((SELECT id FROM taxonomy_terms WHERE slug = 'family-constellation' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'bert hellinger'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nutrition' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'nutritionist'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nutrition' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'nutritional'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nutrition' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'dietitian'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nutrition' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'diet'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nutrition' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'sports nutrition'),
((SELECT id FROM taxonomy_terms WHERE slug = 'herbalism' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'herbalist'),
((SELECT id FROM taxonomy_terms WHERE slug = 'herbalism' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'botanical'),
((SELECT id FROM taxonomy_terms WHERE slug = 'herbalism' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'apothecary'),
((SELECT id FROM taxonomy_terms WHERE slug = 'herbalism' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'herbal medicine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'herbalism' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'plant medicine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'herbalism' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'flower essence'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ayurveda' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'ayurvedic'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ayurveda' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'panchakarma'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ayurveda' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'dosha'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ayurveda' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'abhyanga'),
((SELECT id FROM taxonomy_terms WHERE slug = 'birth-doula' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'doula'),
((SELECT id FROM taxonomy_terms WHERE slug = 'birth-doula' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'birth support'),
((SELECT id FROM taxonomy_terms WHERE slug = 'birth-doula' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'labor support'),
((SELECT id FROM taxonomy_terms WHERE slug = 'birth-doula' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'postpartum doula'),
((SELECT id FROM taxonomy_terms WHERE slug = 'midwife' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'midwifery'),
((SELECT id FROM taxonomy_terms WHERE slug = 'midwife' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'certified midwife'),
((SELECT id FROM taxonomy_terms WHERE slug = 'midwife' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'cnm'),
((SELECT id FROM taxonomy_terms WHERE slug = 'midwife' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'nurse midwife'),
((SELECT id FROM taxonomy_terms WHERE slug = 'midwife' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'home birth'),
((SELECT id FROM taxonomy_terms WHERE slug = 'astrology' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'astrologer'),
((SELECT id FROM taxonomy_terms WHERE slug = 'astrology' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'birth chart'),
((SELECT id FROM taxonomy_terms WHERE slug = 'astrology' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'natal chart'),
((SELECT id FROM taxonomy_terms WHERE slug = 'astrology' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'horoscope'),
((SELECT id FROM taxonomy_terms WHERE slug = 'astrology' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'human design'),
((SELECT id FROM taxonomy_terms WHERE slug = 'astrology' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'gene keys'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'psychic reading'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'tarot'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'oracle'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'medium'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'clairvoyant'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'numerology'),
((SELECT id FROM taxonomy_terms WHERE slug = 'psychic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'intuitive reading'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nature-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'forest bathing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nature-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'ecotherapy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nature-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'nature healing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nature-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'wilderness therapy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'nature-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'shinrin-yoku'),
((SELECT id FROM taxonomy_terms WHERE slug = 'art-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'art therapist'),
((SELECT id FROM taxonomy_terms WHERE slug = 'art-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'creative arts therapy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'art-therapy' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'modality')), 'expressive arts');

-- ── Concern aliases ─────────────────────────────────────────────────────────
INSERT INTO taxonomy_aliases (term_id, alias) VALUES
((SELECT id FROM taxonomy_terms WHERE slug = 'anxiety' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'anxious'),
((SELECT id FROM taxonomy_terms WHERE slug = 'anxiety' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'panic'),
((SELECT id FROM taxonomy_terms WHERE slug = 'anxiety' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'panic attacks'),
((SELECT id FROM taxonomy_terms WHERE slug = 'anxiety' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'worry'),
((SELECT id FROM taxonomy_terms WHERE slug = 'anxiety' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'social anxiety'),
((SELECT id FROM taxonomy_terms WHERE slug = 'stress' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'stressed'),
((SELECT id FROM taxonomy_terms WHERE slug = 'stress' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'stress relief'),
((SELECT id FROM taxonomy_terms WHERE slug = 'stress' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'stress management'),
((SELECT id FROM taxonomy_terms WHERE slug = 'stress' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'relaxation'),
((SELECT id FROM taxonomy_terms WHERE slug = 'stress' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'tension'),
((SELECT id FROM taxonomy_terms WHERE slug = 'chronic-pain' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'pain'),
((SELECT id FROM taxonomy_terms WHERE slug = 'chronic-pain' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'back pain'),
((SELECT id FROM taxonomy_terms WHERE slug = 'chronic-pain' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'neck pain'),
((SELECT id FROM taxonomy_terms WHERE slug = 'chronic-pain' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'pain management'),
((SELECT id FROM taxonomy_terms WHERE slug = 'depression' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'depressed'),
((SELECT id FROM taxonomy_terms WHERE slug = 'depression' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'low mood'),
((SELECT id FROM taxonomy_terms WHERE slug = 'depression' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'sadness'),
((SELECT id FROM taxonomy_terms WHERE slug = 'grief' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'loss'),
((SELECT id FROM taxonomy_terms WHERE slug = 'grief' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'bereavement'),
((SELECT id FROM taxonomy_terms WHERE slug = 'grief' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'mourning'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'ptsd'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'traumatic'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'childhood trauma'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'complex trauma'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'cptsd'),
((SELECT id FROM taxonomy_terms WHERE slug = 'fertility' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'trying to conceive'),
((SELECT id FROM taxonomy_terms WHERE slug = 'fertility' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'ttc'),
((SELECT id FROM taxonomy_terms WHERE slug = 'fertility' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'infertility'),
((SELECT id FROM taxonomy_terms WHERE slug = 'fertility' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'conception'),
((SELECT id FROM taxonomy_terms WHERE slug = 'womens-health' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'female health'),
((SELECT id FROM taxonomy_terms WHERE slug = 'womens-health' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'feminine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'spiritual-growth' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'spiritual awakening'),
((SELECT id FROM taxonomy_terms WHERE slug = 'spiritual-growth' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'enlightenment'),
((SELECT id FROM taxonomy_terms WHERE slug = 'spiritual-growth' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'consciousness'),
((SELECT id FROM taxonomy_terms WHERE slug = 'spiritual-growth' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'higher self'),
((SELECT id FROM taxonomy_terms WHERE slug = 'self-discovery' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'personal growth'),
((SELECT id FROM taxonomy_terms WHERE slug = 'self-discovery' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'self improvement'),
((SELECT id FROM taxonomy_terms WHERE slug = 'self-discovery' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'transformation'),
((SELECT id FROM taxonomy_terms WHERE slug = 'self-discovery' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'finding myself'),
((SELECT id FROM taxonomy_terms WHERE slug = 'burnout' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'burnt out'),
((SELECT id FROM taxonomy_terms WHERE slug = 'burnout' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'adrenal fatigue'),
((SELECT id FROM taxonomy_terms WHERE slug = 'burnout' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'exhaustion'),
((SELECT id FROM taxonomy_terms WHERE slug = 'insomnia' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'sleep'),
((SELECT id FROM taxonomy_terms WHERE slug = 'insomnia' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'sleep problems'),
((SELECT id FROM taxonomy_terms WHERE slug = 'insomnia' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'sleep issues'),
((SELECT id FROM taxonomy_terms WHERE slug = 'gut-health' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'digestion'),
((SELECT id FROM taxonomy_terms WHERE slug = 'gut-health' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'digestive issues'),
((SELECT id FROM taxonomy_terms WHERE slug = 'gut-health' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'bloating'),
((SELECT id FROM taxonomy_terms WHERE slug = 'gut-health' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'ibs'),
((SELECT id FROM taxonomy_terms WHERE slug = 'sports-recovery' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'athletic recovery'),
((SELECT id FROM taxonomy_terms WHERE slug = 'sports-recovery' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'sports injury'),
((SELECT id FROM taxonomy_terms WHERE slug = 'sports-recovery' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'muscle recovery'),
((SELECT id FROM taxonomy_terms WHERE slug = 'prenatal-care' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'pregnancy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'prenatal-care' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'pregnant'),
((SELECT id FROM taxonomy_terms WHERE slug = 'prenatal-care' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'expecting'),
((SELECT id FROM taxonomy_terms WHERE slug = 'prenatal-care' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'prenatal'),
((SELECT id FROM taxonomy_terms WHERE slug = 'postpartum-recovery' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'postpartum'),
((SELECT id FROM taxonomy_terms WHERE slug = 'postpartum-recovery' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'after birth'),
((SELECT id FROM taxonomy_terms WHERE slug = 'postpartum-recovery' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'new mom'),
((SELECT id FROM taxonomy_terms WHERE slug = 'relationship-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'relationship issues'),
((SELECT id FROM taxonomy_terms WHERE slug = 'relationship-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'couples therapy'),
((SELECT id FROM taxonomy_terms WHERE slug = 'relationship-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'marriage'),
((SELECT id FROM taxonomy_terms WHERE slug = 'relationship-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'divorce'),
((SELECT id FROM taxonomy_terms WHERE slug = 'relationship-healing' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'concern')), 'codependency');

-- ── Approach aliases ────────────────────────────────────────────────────────
INSERT INTO taxonomy_aliases (term_id, alias) VALUES
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma-informed' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'trauma sensitive'),
((SELECT id FROM taxonomy_terms WHERE slug = 'trauma-informed' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'trauma aware'),
((SELECT id FROM taxonomy_terms WHERE slug = 'gentle' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'soft'),
((SELECT id FROM taxonomy_terms WHERE slug = 'gentle' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'nurturing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'gentle' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'soothing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'gentle' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'calming'),
((SELECT id FROM taxonomy_terms WHERE slug = 'spiritual' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'sacred'),
((SELECT id FROM taxonomy_terms WHERE slug = 'spiritual' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'divine'),
((SELECT id FROM taxonomy_terms WHERE slug = 'spiritual' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'metaphysical'),
((SELECT id FROM taxonomy_terms WHERE slug = 'spiritual' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'mystical'),
((SELECT id FROM taxonomy_terms WHERE slug = 'body-based' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'body centered'),
((SELECT id FROM taxonomy_terms WHERE slug = 'body-based' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'body oriented'),
((SELECT id FROM taxonomy_terms WHERE slug = 'body-based' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'embodied'),
((SELECT id FROM taxonomy_terms WHERE slug = 'clinical' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'medical'),
((SELECT id FROM taxonomy_terms WHERE slug = 'clinical' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'evidence based'),
((SELECT id FROM taxonomy_terms WHERE slug = 'clinical' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'science based'),
((SELECT id FROM taxonomy_terms WHERE slug = 'integrative' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'multi modal'),
((SELECT id FROM taxonomy_terms WHERE slug = 'integrative' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'comprehensive'),
((SELECT id FROM taxonomy_terms WHERE slug = 'holistic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'whole person'),
((SELECT id FROM taxonomy_terms WHERE slug = 'holistic' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'mind body spirit'),
((SELECT id FROM taxonomy_terms WHERE slug = 'indigenous' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'ancestral'),
((SELECT id FROM taxonomy_terms WHERE slug = 'indigenous' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'traditional healing'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ceremonial' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'sacred space'),
((SELECT id FROM taxonomy_terms WHERE slug = 'ceremonial' AND axis_id = (SELECT id FROM taxonomy_axes WHERE slug = 'approach')), 'prayer');
